version: "3.9"

services:

  browser-box:
    build:
      context: .
      dockerfile: dockerfile
    container_name: browser-box
    ports:
      - "6080:6080"
      - "8554:8554"
      - "8889:8889"
      - "9222:9222"
    networks:
      - app-network

  runner:
    build:
      context: ./runner
      dockerfile: dockerfile
    container_name: runner
    depends_on:
      - browser-box
    networks:
      - app-network

networks:
  app-network:
    driver: bridge